import { LandingModule } from '@modules'
import { type NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-primary to-secondary/10 bg-primary z-10">
        <div className='w-full h-full bg-blur-bg bg-cover bg-top bg-no-repeat'>
          <div className="text-white w-[80%] mx-auto">
            <LandingModule />
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
