import { SkillType } from './interface'

export const SKILLS: SkillType = {
  Python: {
    name: 'Python',
    logo: '/images/logo/python.svg',
    link: 'https://www.python.org/',
    color: '#37E888',
  },
  Java: {
    name: 'Java',
    logo: '/images/logo/java.svg',
    link: 'https://www.java.com/',
    color: '#37E888',
  },
  TypeScript: {
    name: 'TypeScript',
    logo: '/images/logo/typescript.svg',
    link: 'https://www.typescriptlang.org/',
    color: '#37E888',
  },
  Go: {
    name: 'Go',
    logo: '/images/logo/go.svg',
    link: 'https://go.dev/',
    color: '#37E888',
  },
  NextJS: {
    name: 'Next.js',
    logo: '/images/logo/nextjs.png',
    link: 'https://nextjs.org/',
    color: '#95F9C3',
  },
  ReactJS: {
    name: 'ReactJS',
    logo: '/images/logo/reactjs.svg',
    link: 'https://react.dev/',
    color: '#95F9C3',
  },
  ExpressJS: {
    name: 'ExpressJS',
    logo: '/images/logo/express.svg',
    link: 'https://expressjs.com/',
    color: '#95F9C3',
  },
  Fiber: {
    name: 'Fiber',
    logo: '/images/logo/fiber.svg',
    link: 'https://gofiber.io/',
    color: '#95F9C3',
  },
  PGX: {
    name: 'PGX',
    logo: '/images/logo/pgx.svg',
    link: 'https://pkg.go.dev/github.com/jackc/pgx/v5',
    color: '#95F9C3',
  },
  tRPC: {
    name: 'tRPC',
    logo: '/images/logo/trpc.svg',
    link: 'https://trpc.io/',
    color: '#95F9C3',
  },
  Django: {
    name: 'Django',
    logo: '/images/logo/django.svg',
    link: 'https://www.djangoproject.com/',
    color: '#95F9C3',
  },
  FastAPI: {
    name: 'FastAPI',
    logo: '/images/logo/fastapi.svg',
    link: 'https://fastapi.tiangolo.com/',
    color: '#95F9C3',
  },
  SpringBoot: {
    name: 'SpringBoot',
    logo: '/images/logo/springboot.svg',
    link: 'https://spring.io/projects/spring-boot/',
    color: '#95F9C3',
  },
  Strapi: {
    name: 'Strapi',
    logo: '/images/logo/strapi.svg',
    link: 'https://strapi.io/',
    color: '#95F9C3',
  },
  Prisma: {
    name: 'Prisma',
    logo: '/images/logo/prisma.svg',
    link: 'https://www.prisma.io/',
    color: '#95F9C3',
  },
  Redis: {
    name: 'Redis',
    logo: '/images/logo/redis.svg',
    link: 'https://www.redis.io/',
    color: '#95F9C3',
  },
  GoogleAPI: {
    name: 'Google API',
    logo: '/images/logo/google-api.svg',
    link: 'https://console.cloud.google.com/',
    color: '#95F9C3',
  },
  AWS: {
    name: 'AWS',
    logo: '/images/logo/aws.svg',
    link: 'https://console.aws.amazon.com/',
    color: '#95F9C3',
  },
  GCP: {
    name: 'GCP',
    logo: '/images/logo/gcp.svg',
    link: 'https://console.cloud.google.com',
    color: '#95F9C3',
  },
  PostgreSQL: {
    name: 'PostgreSQL',
    logo: '/images/logo/postgresql.svg',
    link: 'https://www.postgresql.org/',
    color: '#9BF6FF',
  },
  MySQL: {
    name: 'MySQL',
    logo: '/images/logo/mysql.svg',
    link: 'https://www.mysql.com/',
    color: '#9BF6FF',
  },
  Pentaho: {
    name: 'Pentaho',
    logo: '/images/logo/pentaho.svg',
    link: 'https://www.hitachivantara.com/en-us/products/pentaho-plus-platform/data-integration-analytics.html',
    color: '#9BF6FF',
  },
  Tableau: {
    name: 'Tableau',
    logo: '/images/logo/tableau.svg',
    link: 'https://www.tableau.com/',
    color: '#9BF6FF',
  },
  ChakraUI: {
    name: 'Chakra UI',
    logo: '/images/logo/chakra-ui.svg',
    link: 'https://chakra-ui.com/',
    color: '#A0C4FF',
  },
  TailwindCSS: {
    name: 'Tailwind CSS',
    logo: '/images/logo/tailwind.svg',
    link: 'https://tailwindcss.com/',
    color: '#A0C4FF',
  },
  GraphicDesign: {
    name: 'Graphic Design',
    logo: '/images/logo/graphicdesign.svg',
    link: '#',
    color: '#A0C4FF',
  },
  ML: {
    name: 'ML',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  CV: {
    name: 'CV',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  NLP: {
    name: 'NLP',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  SLP: {
    name: 'SLP',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  LLM: {
    name: 'LLM',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  VLM: {
    name: 'VLM',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  HCI: {
    name: 'HCI',
    logo: '',
    link: '#',
    color: '#FFD6A5',
  },
  OpenCV: {
    name: 'OpenCV',
    logo: '/images/logo/chakra-ui.svg',
    link: 'https://opencv.org/',
    color: '#FFD6A5',
  },
  Tensorflow: {
    name: 'Tensorflow',
    logo: '/images/logo/tensorflow.svg',
    link: 'https://www.tensorflow.org/',
    color: '#FFD6A5',
  },
  Pytorch: {
    name: 'Pytorch',
    logo: '/images/logo/pytorch.svg',
    link: 'https://pytorch.org/',
    color: '#FFD6A5',
  },
  HuggingFace: {
    name: 'Hugging Face',
    logo: '/images/logo/huggingface.svg',
    link: 'https://huggingface.co/',
    color: '#FFD6A5',
  },
  LangChain: {
    name: 'LangChain',
    logo: '/images/logo/langchain.svg',
    link: 'https://langchain.com/',
    color: '#FFD6A5',
  },
  LangGraph: {
    name: 'LangGraph',
    logo: '/images/logo/langgraph.svg',
    link: '',
    color: '#FFD6A5',
  },
  KnowledgeGraph: {
    name: 'Knowledge Graph',
    logo: '/images/logo/kg.svg',
    link: '',
    color: '#FFD6A5',
  },
  RAG: {
    name: 'RAG',
    logo: '/images/logo/rag.svg',
    link: '',
    color: '#FFD6A5',
  },
  SPARQL: {
    name: 'SPARQL',
    logo: '/images/logo/sparql.svg',
    link: '',
    color: '#FFD6A5',
  },
  Gephi: {
    name: 'Gephi',
    logo: '/images/logo/gephi.svg',
    link: 'https://gephi.org/',
    color: '#FFD6A5',
  },
  RL: {
    name: 'RL',
    logo: '/images/logo/rl.svg',
    link: '',
    color: '#FFD6A5',
  },
}
